version: '3.7'
services:
  mysql:
    image: mysql
    container_name: crud
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbitmq_management

    ports:
      - 5672:5672 # (erlang) communication between the nodes and CLI tool
      - 15672:15672 # communication with the web management API
    environment:
      - RABBITMQ_DEFAULT_USER=guess
      - RABBITMQ_DEFAULT_PASS=guess
    restart: always
